
# GeoName
GET http://api.geonames.org/postalCodeSearchJSON?placename=Montreal&maxRows=10&username=ardeshir

# weatherbit

# GET https://api.weatherbit.io/v2.0/forecast/daily?key=00d059bd2cfe43f4b72bd15204c392f4&lat=45.50884&lon=-73.58781


# pixabay
# GET https://pixabay.com/api/?key=19047406-4088c00f011e020a9d4ae2608&q=Montreal&image_type=photo&category=nature&per_page=3